# Generated by Django 4.2.1 on 2023-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_menuitem_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='imgUrl',
            field=models.URLField(db_index=True, default=''),
        ),
    ]
