# Generated by Django 4.2.1 on 2023-06-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_menuitem_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='desc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='img_url',
            field=models.URLField(db_index=True, default=None, max_length=255),
        ),
    ]
